[project]
name = "write-voxel-logo"
version = "0.0.0"
description = "Example of generating an animated 3D voxel logo using Foxglove's VoxelGrid schema"
authors = [{ name = "Foxglove", email = "support@foxglove.dev" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["foxglove-sdk>=0.4.0"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
foxglove-sdk = { path = "../../foxglove-sdk", develop = true }

[tool.poetry.group.dev.dependencies]
mypy = "^1"
