[package]
name = "prost-protobuf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "prost_protobuf"
path = "src/main.rs"

[dependencies]
bytes.workspace = true
env_logger = "0.11.8"
foxglove = { version = "0.8.1", path = "../../foxglove", features = ["derive", "schemars"] }
foxglove_derive = { version = "0.8.1", path = "../../foxglove_derive" }
prost.workspace = true
schemars = "0.9.0"
serde.workspace = true

[lints]
workspace = true

[build-dependencies]
anyhow = "1.0.98"
prost.workspace = true
prost-build.workspace = true
prost-types.workspace = true
walkdir = "2.5.0"
